CREATE TABLE IF NOT EXISTS "GroupMember" (
	id SERIAL PRIMARY KEY,
	group_id INTEGER NOT NULL REFERENCES "Group" (id) ON DELETE CASCADE,
	user_id INTEGER NOT NULL REFERENCES "User" (id) ON DELETE CASCADE,
	joined_at TIMESTAMP NOT NULL
);
