CREATE TABLE IF NOT EXISTS reactions (
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
	message_id INTEGER REFERENCES messages (id) ON DELETE CASCADE,
	emoji VARCHAR(8) NOT NULL
);
