CREATE TABLE IF NOT EXISTS "Reaction" (
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES "User" (id) ON DELETE CASCADE,
	message_id INTEGER REFERENCES "Message" (id) ON DELETE CASCADE,
	emoji VARCHAR(8) NOT NULL
);
