CREATE TABLE IF NOT EXISTS "Message" (
	id SERIAL PRIMARY KEY,
	author_id INTEGER REFERENCES "User" (id) ON DELETE SET NULL,
	groups_id INTEGER REFERENCES "Group" (id) ON DELETE CASCADE,
	content TEXT NOT NULL,
	time TIMESTAMP NOT NULL,
	proof BOOLEAN NOT NULL DEFAULT FALSE
);
